apiVersion: apps/v1
kind: Deployment
metadata:
  name: twas-deployment
  labels:
    app: twas
spec:
  selector:
    matchLabels:
      app: twas
  template:
    metadata:
      labels:
        app: twas
    spec:
      containers:
      - name: twas-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/twas-my-base:[was-version]
        ports:
        - containerPort: 9060
        - containerPort: 9080
      imagePullSecrets:
      - name: docker-user-secret
--- 
apiVersion: v1
kind: Service
metadata:
  name: twas-service
spec:
  selector:
    app: twas
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
---
apiVersion: v1
kind: Route
metadata:
  name: twas-route
spec:
  to:
    kind: Service
    name: twas-service
---
apiVersion: v1
kind: Service
metadata:
  name: twas-admin-service
spec:
  selector:
    app: twas
  ports:
  - protocol: TCP
    port: 9060
    targetPort: 9060
---
apiVersion: v1
kind: Route
metadata:
  name: twas-admin-route
spec:
  to:
    kind: Service
    name: twas-admin-service

